/*
* Generated file
*
* Generated from: yang module name: ofoverlay-provider-impl yang module local name: ofoverlay-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jun 24 15:06:29 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.ofoverlay_provider.impl;
public class OFOverlayProviderModuleFactory extends org.opendaylight.controller.config.yang.config.ofoverlay_provider.impl.AbstractOFOverlayProviderModuleFactory {

}
