/*
* Generated file
*
* Generated from: yang module name: ovssfc-provider-impl yang module local name: ovssfc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Nov 03 20:21:14 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.ovssfc_provider.impl;
public class OvssfcProviderModuleFactory extends org.opendaylight.controller.config.yang.config.ovssfc_provider.impl.AbstractOvssfcProviderModuleFactory {

}
