/*
* Generated file
*
* Generated from: yang module name: opflex-provider-impl yang module local name: opflex-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jun 11 17:14:35 UTC 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.opflex_provider.impl;
public class OpflexProviderModuleFactory extends org.opendaylight.controller.config.yang.config.opflex_provider.impl.AbstractOpflexProviderModuleFactory {

}
