$deps = [
    'autoconf',
    'automake',
    'bc',
    'bridge-utils',
    'build-essential',
    'conntrack',
    'curl',
    'debhelper',
    'dkms',
    'dnsmasq-base',
    'dnsmasq-utils',
    'ebtables',
    'euca2ools',
    'gawk',
    'gcc',
    'genisoimage',
    'git',
    'graphviz',
    'iptables',
    'iputils-arping',
    'iputils-ping',
    'kpartx',
    'libffi-dev',
    'libjs-jquery-tablesorter',
    'libssl-dev',
    'libtool',
    'libyaml-dev',
    'lsof',
    'lvm2',
    'open-iscsi',
    'openssh-server',
    'openssl',
    'parted',
    'pm-utils',
    'psmisc',
    'pylint',
    'python-all',
    'python-boto',
    'python-cheetah',
    'python-dev',
    'python-eventlet',
    'python-feedparser',
    'python-greenlet',
    'python-iso8601',
    'python-kombu',
    'python-libxml2',
    'python-lockfile',
    'python-lxml',
    'python-m2crypto',
    'python-migrate',
    'python-mox',
    'python-mysql.connector',
    'python-mysqldb',
    'python-numpy',
    'python-paste',
    'python-pastedeploy',
    'python-pyudev',
    'python-qt4',
    'python-routes',
    'python-setuptools',
    'python-sqlalchemy',
    'python-suds',
    'python-tempita',
    'python-twisted-conch',
    'python-unittest2',
    'python-virtualenv',
    'python-xattr',
    'python-zopeinterface',
    'python2.7',
    'screen',
    'sg3-utils',
    'socat',
    'sqlite3',
    'sudo',
    'sysfsutils',
    'tar',
    'tcpdump',
    'unzip',
    'vim',
    'vlan',
    'wget',
    'xbase-clients',
    'wireshark'
]

$hosts = hiera('hosts')

file { '/etc/hosts':
    ensure  => file,
    owner   => 'root',
    group   => 'root',
    content => template('/vagrant/puppet/templates/hosts.erb')
}

package { $deps:
    ensure   => installed,
}

exec {"Download Open vSwitch":
    command => "wget https://raw.githubusercontent.com/pritesh/ovs/nsh-v8/third-party/start-ovs-deb.sh",
    cwd     => "/home/vagrant",
    creates => "/home/vagrant/start-ovs-deb.sh",
    path    => $::path,
    user    => 'vagrant'
}

exec { 'Extract Open vSwitch':
    command => "bash /home/vagrant/start-ovs-deb.sh",
    cwd     => '/home/vagrant',
    user    => 'root',
    path    => $::path,
    timeout => 0,
    require => Exec['Download Open vSwitch']
}
