/*
* Copyright (c) 2013 Cisco Systems, Inc. and others.  All rights reserved.
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License v1.0 which accompanies this distribution,
* and is available at http://www.eclipse.org/legal/epl-v10.html
*/
/*
* Generated file
*
* Generated from: yang module name: endpoint-provider-impl yang module local name: endpoint-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Apr 24 18:12:49 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.endpoint_provider.impl;
public class EndpointProviderModuleFactory extends org.opendaylight.controller.config.yang.config.endpoint_provider.impl.AbstractEndpointProviderModuleFactory {

}
