/*
 * Generated file
 * 
 * Generated from: yang module name: faas-provider-impl yang module local name: faas-provider-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Fri Oct 09 16:39:53 EDT 2015
 * 
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.config.faas_provider.impl;

public class FaasProviderModuleFactory extends
        org.opendaylight.controller.config.yang.config.faas_provider.impl.AbstractFaasProviderModuleFactory {

}
