/*
* Generated file
*
* Generated from: yang module name: openstack-endpoint-provider-impl yang module local name: openstack-endpoint-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Dec 04 15:28:49 PST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.openstack_endpoint_provider.impl;
public class OpenstackEndpointProviderModuleFactory extends org.opendaylight.controller.config.yang.config.openstack_endpoint_provider.impl.AbstractOpenstackEndpointProviderModuleFactory {

}
